### ISSUE TITLE
Control key is not considered as modifier on keyboard layout preview

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/globalization#228]
Some keyboards have control key (scan code `1D`) as and/or right control (scan code `E0 1D`) as modifiers and should behave as toggle keys on keyboard preview page.

For example [Canadian Multilingual Standard Keyboard](https://learn.microsoft.com/en-us/globalization/keyboards/kbdcan) have many characters that can be only input with `VK_OEM_8` (scan code `E0 1D` - right control key) or `VK_SHIFT + VK_OEM_8` key modifiers and cannot be seen on keyboard preview.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/1285934/212482930-6c29fc22-bedc-4965-96dd-5ef8973a11f8.png">

See also [Canadian Multilingual Standard Layout Shift States on https://kbdlayout.info/](https://kbdlayout.info/kbdcan/shiftstates).

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/1285934/212483021-3d3fd818-2392-44f0-a9ba-1c93d0c4f20b.png">

**Comment by DJm00n** [comment]
FYI @jowilco

**Comment by jowilco** [comment]
@DJm00n - Just acknowledging this issue. It might be a little more complex than #222.

**Comment by DJm00n** [comment]
Thanks for the update. It's not something that's blocking me or my work. Take your time.

**Comment by jowilco** [comment]
@DJm00n - Sorry for the delay. Changes are live - please see PR #244 .

The Canadian Multilingual Keyboard now has the Right Ctrl / OEM 8 behavior. The only other keyboard that currently uses an alternate shift state is Korean; however, Korean input is dependent on the IDE, so it doesn't really take advantage of native alternate shift state behavior.

While implementing this, I noticed that other keyboards had not been implemented correctly (e.g., Czech Shift vs. Caps behavior on the top row of keys) and these should now behave correctly.

Thank you again for bringing this to our attention so that we could improve the experience for everyone.

Please close this issue if you feel that it is now resolved.

Sincerely,
John
